/*
 *
 *	Adventure Creator
 *	by Chris Burton, 2013-2016
 *	
 *	"RuntimeLanguage.cs"
 * 
 *	This script contains all language data for the game at runtime.
 *	It transfers data from the Speech Manaager to itself when the game begins.
 * 
 */

using UnityEngine;
using System.Collections;
using System.Collections.Generic;

namespace AC
{

	#if !(UNITY_4_6 || UNITY_4_7 || UNITY_5_0)
	[HelpURL("http://www.adventurecreator.org/scripting-guide/class_a_c_1_1_runtime_languages.html")]
	#endif
	public class RuntimeLanguages : MonoBehaviour
	{

		private List<SpeechLine> lines = new List<SpeechLine>();
		private List<string> languages = new List<string>();


		public void OnAwake ()
		{
			TransferFromManager ();
		}


		/** The names of the game's languages. The first is always "Original". */
		public List<string> Languages
		{
			get
			{
				return languages;
			}
		}

		
		private void TransferFromManager ()
		{
			if (AdvGame.GetReferences () && AdvGame.GetReferences ().speechManager)
			{
				SpeechManager speechManager = AdvGame.GetReferences ().speechManager;
				
				languages.Clear ();
				foreach (string _language in speechManager.languages)
				{
					languages.Add (_language);
				}

				lines.Clear ();
				foreach (SpeechLine line in speechManager.lines)
				{
					lines.Add (new SpeechLine (line));
				}
			}
		}


		/**
		 * <summary>Gets the translation of a line of text.</summary>
		 * <param name = "originalText">The line in its original language.</param>
		 * <param name = "_lineID">The translation ID number generated by SpeechManager's PopulateList() function</param>
		 * <param name = "language">The index number of the language to return the line in, where 0 = the game's original language. </param>
		 * <returns>The translation of the line, if it exist. If a translation does not exist, then the original line will be returned.</returns>
		 */
		public string GetTranslation (string originalText, int _lineID, int language)
		{
			if (language == 0 || originalText == "")
			{
				return originalText;
			}
			
			if (_lineID == -1 || language <= 0)
			{
				ACDebug.Log ("Cannot find translation for '" + originalText + "' because the text has not been added to the Speech Manager.");
				return originalText;
			}
			else
			{
				foreach (SpeechLine line in AdvGame.GetReferences ().speechManager.lines)
				{
					if (line.lineID == _lineID)
					{
						if (line.translationText.Count > (language-1))
						{
							return line.translationText [language-1];
						}
						else
						{
							ACDebug.LogWarning ("A translation is being requested that does not exist!");
						}
					}
				}
			}
			return "";
		}


		private void CreateLanguage (string name)
		{
			languages.Add (name);
			
			foreach (SpeechLine line in lines)
			{
				line.translationText.Add (line.text);
			}
		}


		/**
		 * <summary>Imports a translation CSV file (as generated by the Speech Manager) into the game - either as a new language, or as an update to an existing one.</summary>
		 * <param name = "textAsset">The CSV file as a text asset.</param>
		 * <param name = "languageName">The name of the language.  If a language by this name already exists in the system, the import process will update it.</param>
		 */
		public void ImportRuntimeTranslation (TextAsset textAsset, string languageName)
		{
			if (textAsset.text.Length > 0)
			{
				if (!languages.Contains (languageName))
				{
					CreateLanguage (languageName);
					int i = languages.Count - 1;
					ProcessTranslationFile (i, textAsset.text);
				}
				else
				{
					int i = languages.IndexOf (languageName);
					ProcessTranslationFile (i, textAsset.text);
				}
			}
		}
		
		
		private void ProcessTranslationFile (int i, string csvText)
		{
			string [,] csvOutput = CSVReader.SplitCsvGrid (csvText);
			
			int lineID = 0;
			string translationText = "";
			string owner = "";
			
			for (int y = 1; y < csvOutput.GetLength (1); y++)
			{
				if (csvOutput [0,y] != null && csvOutput [0,y].Length > 0)
				{
					lineID = -1;
					if (int.TryParse (csvOutput [0,y], out lineID))
					{
						translationText = csvOutput [3, y];//.Replace (CSVReader.csvTemp, CSVReader.csvComma);
						string typeText = csvOutput [1, y];//.Replace (CSVReader.csvTemp, CSVReader.csvComma);
						
						if (typeText.Contains ("JournalEntry (Page "))
						{
							owner = typeText.Replace ("JournalEntry (", "");
							owner = owner.Replace (")", "");
						}
						else
						{
							owner = "";
						}
						UpdateTranslation (i, lineID, owner, AddLineBreaks (translationText));
					}
					else
					{
						ACDebug.LogWarning ("Error importing translation (ID:" + csvOutput [0,y] + ") - make sure that the CSV file is delimited by a '" + CSVReader.csvDelimiter + "' character.");
					}
				}
			}
		}


		private string AddLineBreaks (string text)
		{
			return (text.Replace ("[break]", "\n"));
		}


		private void UpdateTranslation (int i, int _lineID, string _owner, string translationText)
		{
			foreach (SpeechLine line in lines)
			{
				if (line.lineID == _lineID)
				{
					line.translationText [i-1] = translationText;
				}
			}
		}

	}

}